services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-init:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka-init
    depends_on:
      - kafka
    command: >
      bash -c "
        cub kafka-ready -b kafka:29092 1 30 &&
        kafka-topics --create --topic brapi_stock_quotes --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 &&
        kafka-topics --create --topic postgres_stock_quotes --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1
      "

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: "stock_data"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka-init
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        echo 'Esperando o MinIO estar pronto para comandos mc...' &&
        /usr/bin/mc alias set minio_local http://minio:9000 minioadmin minioadmin &&
        until /usr/bin/mc ls minio_local/; do
          echo 'MinIO ainda não está disponível para comandos mc (provavelmente ainda inicializando ou problemas de acesso), esperando...'
          sleep 5
        done &&
        echo 'MinIO está acessível. Criando buckets...' &&
        /usr/bin/mc mb -p minio_local/raw &&
        /usr/bin/mc mb -p minio_local/processing &&
        /usr/bin/mc mb -p minio_local/loaded &&
        echo 'Buckets do MinIO criados com sucesso.' &&
        exit 0
      "

  kafka_to_minio_raw:
    build:
      context: ./ingestion_services/kafka_to_minio_raw
      dockerfile: Dockerfile
    container_name: kafka_to_minio_raw
    depends_on:
      - kafka-init
      - minio-init
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_RAW_BUCKET: "raw"

  brapi_producer:
    build:
      context: .
      dockerfile: ./ingestion_services/brapi_producer/Dockerfile
    container_name: brapi_producer
    depends_on:
      - kafka-init
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      BRAPI_TOPIC: "brapi_stock_quotes"
      BRAPI_TOKEN: "b38wCXyAUpwq5vuSstYFcY"

  yfinance_to_postgres:
    build:
      context: .
      dockerfile: ./ingestion_services/yfinance_to_postgres/Dockerfile
    container_name: yfinance_to_postgres
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "stock_data"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

  postgres_producer:
    build:
      context: .
      dockerfile: ./ingestion_services/postgres_producer/Dockerfile
    container_name: postgres_producer
    depends_on:
      - kafka-init
      - yfinance_to_postgres
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      YFINANCE_TOPIC: "postgres_stock_quotes"
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "stock_data"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

  batch_ingestion:
    build:
      context: .
      dockerfile: ./ingestion_services/batch_ingestion/Dockerfile
    container_name: batch_ingestion
    depends_on:
      - minio-init
    volumes:
      - ./ingestion_services/batch_ingestion/COTAHIST_A2009_to_A2020_P.csv:/app/data/COTAHIST_A2009_to_A2020_P.csv:ro
    environment:
      SOURCE_FILE_PATH: "/app/data/COTAHIST_A2009_to_A2020_P.csv"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_RAW_BUCKET: "raw"

  data_processing:
    build:
      context: ./ingestion_services/data_processing
      dockerfile: Dockerfile
    container_name: data_processing
    depends_on:
      batch_ingestion:
        condition: service_completed_successfully
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_RAW_BUCKET: "raw"
      MINIO_PROCESSING_BUCKET: "processing"
      MINIO_LOADED_BUCKET: "loaded"
volumes:
  postgres_data:
  minio_data:
